### ISSUE TITLE
EFI for Catalina ?

### ISSUE THREAD

**Issue by marciofmjr** [patrickbattisti/macOS-Mojave-Inspiron-5547#2]
Do you have the EFI for Catalina ?

**Comment by 1729patrick** [comment]
Hi,

The the github file upload limit is 10MB and the zip is bigger than 10MB

[EFI in Google Drive](https://drive.google.com/open?id=14Fqx6PM7yP7T8-hM9GNEf3FM6cdBDATS)

Talk me if you need help, good luck 👍

**Comment by marciofmjr** [comment]
Eu coloquei a pasta mas não funcionou :/

Como voce instalou ele ? poderia fazer um tutorial falando o passo a passo ?

Obrigado !

**Comment by dyohan9** [comment]
> Hi,
> 
> 
> 
> The the github file upload limit is 10MB and the zip is bigger than 10MB
> 
> 
> 
> [EFI in Google Drive](https://drive.google.com/open?id=14Fqx6PM7yP7T8-hM9GNEf3FM6cdBDATS)
> 
> 
> 
> Talk me if you need help, good luck 👍 

Então, você poderia disponibilizar um tutorial para o catalina ?

**Comment by marciofmjr** [comment]
> > Hi,
> > The the github file upload limit is 10MB and the zip is bigger than 10MB
> > [EFI in Google Drive](https://drive.google.com/open?id=14Fqx6PM7yP7T8-hM9GNEf3FM6cdBDATS)
> > Talk me if you need help, good luck 👍
> 
> Então, você poderia disponibilizar um tutorial para o catalina ?

ajudaria muito!

**Comment by 1729patrick** [comment]
Olá @marciofmjr,

Esse arquivos apenas funcionarão se o seu processador for o mesmo que o meu. Verifica isso, por favor.

**Comment by mtsbastos18** [comment]
Boa noite @patrickbattisti, eu coloco todos aqueles arquivos dentro da EFI do pen drive e depois instalo o sistema?
