### ISSUE TITLE
Imagem do macOS

### ISSUE THREAD

**Issue by mtsbastos18** [patrickbattisti/macOS-Mojave-Inspiron-5547#3]
Boa tarde patrick. Estou com dificuldade de encontrar a imagem do macOS sem possuir um mac.

Teria alguma dica?

**Comment by wrgoncalves2008** [comment]
Boa Tarde!
Estou com a mesma dificuldade do @mtsbastos18 
Seria possível disponibilizar a imagem ou o link onde podemos baixa-la, por favor?

Obrigado!!

**Comment by 1729patrick** [comment]
Olá @mtsbastos18 e @wrgoncalves2008 ,

Aqui vocês encontram todos os sofwares e SOs disponíveis para download.

`https://support.apple.com/pt_BR/downloads`

Abraço!
